title = "Fermyon Developer"
base_url = ""
about = "Fermyon Developer â€” the home for you as a developer using Fermyon projects and products."
index_site_pages = ["sitemap", "home", "changelog", "hub_list_api"]
prepend_route_info = true

[extra]
copyright = "Fermyon"
github = "https://github.com/fermyon/developer"
twitter = "https://twitter.com/fermyontech"

# Static assets that we need to provide
favicon = "/static/image/icon/favicon.png"
twitter_card_type = "summary"
twitter_card = "/static/image/twitter_card_summary.png"
